"""Native SCM adapter with LocalService identity. No auto elevation.

Installation requires an explicit administrator terminal and an immutable EXE
under Program Files. Agent identity is generated by LocalService, using its own
CurrentUser DPAPI context. A one-use enrollment bootstrap is machine-DPAPI
protected AND ACL-restricted; it is removed as soon as enrollment succeeds.
"""
import ctypes
from ctypes import wintypes as w
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import time
from licensing.contracts import Denied
from licensing.secure_store import DATA_BLOB,SecureStore,dpapi
SERVICE_NAME='ConfiguradorTIAgent'
_SERVICE_STATES={1:'STOPPED',2:'START_PENDING',3:'STOP_PENDING',4:'RUNNING'}
_CONTROL_TIMEOUT=30.0
_POLL_INTERVAL=0.5
_CODE=re.compile(r'[A-Za-z0-9_-]{43}\Z',re.ASCII)

def validate_enrollment_code(code):
    # control_plane.fleet._invite uses secrets.token_urlsafe(32): 43 base64url
    # characters, without padding or whitespace. Never echo invalid input.
    if not isinstance(code,str) or _CODE.fullmatch(code) is None:
        raise Denied('INVALID_ENROLLMENT_CODE')
    return code

def _clipboard_text():
    """Copy at most 44 UTF-16 characters while the Win32 clipboard is open."""
    user=ctypes.WinDLL('user32',use_last_error=True)
    kernel=ctypes.WinDLL('kernel32',use_last_error=True)
    user.OpenClipboard.argtypes=[w.HWND];user.OpenClipboard.restype=w.BOOL
    user.GetClipboardData.argtypes=[w.UINT];user.GetClipboardData.restype=w.HANDLE
    user.CloseClipboard.argtypes=[];user.CloseClipboard.restype=w.BOOL
    kernel.GlobalSize.argtypes=[w.HGLOBAL];kernel.GlobalSize.restype=ctypes.c_size_t
    kernel.GlobalLock.argtypes=[w.HGLOBAL];kernel.GlobalLock.restype=ctypes.c_void_p
    kernel.GlobalUnlock.argtypes=[w.HGLOBAL];kernel.GlobalUnlock.restype=w.BOOL
    if not user.OpenClipboard(None): raise Denied('CLIPBOARD_UNAVAILABLE')
    try:
        handle=user.GetClipboardData(13)  # CF_UNICODETEXT
        if not handle: raise Denied('CLIPBOARD_UNAVAILABLE')
        size=kernel.GlobalSize(handle)
        if size<2: raise Denied('CLIPBOARD_UNAVAILABLE')
        pointer=kernel.GlobalLock(handle)
        if not pointer: raise Denied('CLIPBOARD_UNAVAILABLE')
        try:
            raw=ctypes.string_at(pointer,min(size//2,44)*2)
        finally: kernel.GlobalUnlock(handle)
        try: content=raw.decode('utf-16-le')
        except UnicodeError: raise Denied('INVALID_ENROLLMENT_CODE') from None
        code,separator,_=content.partition('\x00')
        if not separator: raise Denied('INVALID_ENROLLMENT_CODE')
        return validate_enrollment_code(code)
    finally: user.CloseClipboard()

def read_enrollment_code():
    """Secret Windows console input; Ctrl+V supports both host paste and ^V."""
    if os.name!='nt': raise Denied('WINDOWS_REQUIRED')
    if not sys.stdin.isatty(): raise Denied('INTERACTIVE_CONSOLE_REQUIRED')
    import msvcrt
    sys.stderr.write('Código de enrollment (oculto; Ctrl+V para colar): ')
    sys.stderr.flush()
    chars=[]
    try:
        while True:
            try: key=msvcrt.getwch()
            except OSError: raise Denied('SECURE_CONSOLE_UNAVAILABLE') from None
            if key in ('\r','\n'): return validate_enrollment_code(''.join(chars))
            if key in ('\b','\x7f'):
                if chars: chars.pop()
                continue
            if key=='\x16':
                try: paste=_clipboard_text()
                except (Denied,OSError) as exc:
                    if isinstance(exc,Denied) and exc.code!='CLIPBOARD_UNAVAILABLE': raise
                    # Keep the hidden prompt active for manual typing.
                    sys.stderr.write('\nClipboard indisponível; digite o código sem eco: ')
                    sys.stderr.flush()
                    continue
                if len(chars)+len(paste)>43: raise Denied('INVALID_ENROLLMENT_CODE')
                chars.extend(paste)
                continue
            if key in ('\x00','\xe0'):
                try: msvcrt.getwch()  # Non-printable extended-key scan code.
                except OSError: raise Denied('SECURE_CONSOLE_UNAVAILABLE') from None
                continue
            if len(key)!=1 or key not in 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-':
                raise Denied('INVALID_ENROLLMENT_CODE')
            if len(chars)>=43: raise Denied('INVALID_ENROLLMENT_CODE')
            chars.append(key)
    finally:
        sys.stderr.write('\n');sys.stderr.flush()

def state_root():
    if os.name!='nt': raise Denied('WINDOWS_REQUIRED')
    return Path(os.environ['ProgramData'])/'ConfiguradorTI-Agent'
def machine_protect(raw):
    buf=(ctypes.c_ubyte*len(raw)).from_buffer_copy(raw);source=DATA_BLOB(len(raw),buf);out=DATA_BLOB()
    dll=ctypes.WinDLL('crypt32',use_last_error=True);kernel=ctypes.WinDLL('kernel32',use_last_error=True)
    dll.CryptProtectData.argtypes=[ctypes.POINTER(DATA_BLOB),w.LPCWSTR,ctypes.c_void_p,ctypes.c_void_p,ctypes.c_void_p,w.DWORD,ctypes.POINTER(DATA_BLOB)]
    dll.CryptProtectData.restype=w.BOOL;kernel.LocalFree.argtypes=[ctypes.c_void_p];kernel.LocalFree.restype=ctypes.c_void_p
    if not dll.CryptProtectData(ctypes.byref(source),None,None,None,None,5,ctypes.byref(out)): raise Denied('SECURE_STORE_UNAVAILABLE')
    try: return ctypes.string_at(out.pbData,out.cbData)
    finally: kernel.LocalFree(out.pbData)
def system_tool(name,args):
    path=Path(os.environ['SystemRoot'])/'System32'/name
    return subprocess.run([str(path),*args],shell=False,stdin=subprocess.DEVNULL,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL,timeout=30).returncode

def install(config,code):
    validate_enrollment_code(code)  # Before touching ProgramData or the SCM.
    if os.name!='nt': raise Denied('WINDOWS_REQUIRED')
    if not ctypes.windll.shell32.IsUserAnAdmin(): raise Denied('NEEDS_HUMAN')
    exe=Path(sys.executable).resolve();program_files=Path(os.environ['ProgramFiles']).resolve()
    if not getattr(sys,'frozen',False) or program_files not in exe.parents: raise Denied('PROTECTED_EXE_REQUIRED')
    root=state_root();SecureStore(root/'identity.bin',qa=config['qa'])._safe()
    if root.exists(): raise Denied('EXISTING_STATE_PRESERVED')
    root.mkdir(mode=0o700)
    created=False
    try:
        if system_tool('icacls.exe',[str(root),'/inheritance:r','/grant:r','*S-1-5-18:(OI)(CI)F','*S-1-5-32-544:(OI)(CI)F','*S-1-5-19:(OI)(CI)M']): raise Denied('ACL_FAILED')
        (root/'agent-public.json').write_text(json.dumps(config),encoding='utf-8')
        (root/'enrollment.bootstrap').write_bytes(machine_protect(code.encode('utf-8')))
        binary=subprocess.list2cmdline([str(exe),'service-run'])
        if system_tool('sc.exe',['create',SERVICE_NAME,'binPath=',binary,'start=','demand','obj=','NT AUTHORITY\\LocalService','DisplayName=','Configurador TI Agent']):
            raise Denied('SERVICE_INSTALL_FAILED')
        created=True
    finally:
        if not created:
            for name in ('enrollment.bootstrap','agent-public.json'):
                (root/name).unlink(missing_ok=True)
            try: root.rmdir()
            except OSError: pass
    return {'status':'INSTALLED','account':'LocalService','start':'MANUAL'}

def enroll_from_bootstrap(agent,bootstrap,on_ready=None):
    if bootstrap.stat().st_size>4096: raise Denied('INVALID_BOOTSTRAP')
    try: code=dpapi(bootstrap.read_bytes(),True).decode('utf-8')
    except UnicodeError: raise Denied('INVALID_BOOTSTRAP') from None
    try: validate_enrollment_code(code)
    except Denied: raise Denied('INVALID_BOOTSTRAP') from None
    if on_ready: on_ready()
    agent.enroll(code)
    bootstrap.unlink()  # Never remove on a rejected or incomplete enrollment.

def record_service_failure(root,stage,exc):
    """Only fixed, non-secret categories in the existing restricted state dir."""
    if stage not in ('CONFIG','AGENT_INIT','BOOTSTRAP','ENROLLMENT','RUNNING'):
        stage='AGENT_INIT'
    if stage=='BOOTSTRAP': category='BOOTSTRAP_FAILED'
    elif stage=='ENROLLMENT': category='BACKEND_UNAVAILABLE' if isinstance(exc,ConnectionError) else 'ENROLLMENT_REJECTED'
    else: category='SERVICE_RUN_FAILED'
    path=root/'service-diagnostic.json'
    SecureStore(path,qa=True)._safe()
    fd,temp=tempfile.mkstemp(prefix='.service-diagnostic-',dir=root)
    try:
        with os.fdopen(fd,'w',encoding='utf-8') as out:
            json.dump({'status':'FAILED','stage':stage,'code':category},out)
            out.flush();os.fsync(out.fileno())
        os.replace(temp,path)
    finally:
        if os.path.exists(temp): os.unlink(temp)
def query_service(*,include_config=False):
    """Query the local SCM without parsing localized sc.exe output."""
    if os.name!='nt': raise Denied('WINDOWS_REQUIRED')
    class STATUS_PROCESS(ctypes.Structure):
        _fields_=[(n,w.DWORD) for n in ('service_type','current_state','controls_accepted','win32_exit',
                 'service_exit','checkpoint','wait_hint','process_id','service_flags')]
    class CONFIG(ctypes.Structure):
        _fields_=[('service_type',w.DWORD),('start_type',w.DWORD),('error_control',w.DWORD),
                  ('binary',w.LPWSTR),('load_group',w.LPWSTR),('tag',w.DWORD),
                  ('dependencies',w.LPWSTR),('account',w.LPWSTR),('display_name',w.LPWSTR)]
    api=ctypes.WinDLL('advapi32',use_last_error=True)
    api.OpenSCManagerW.argtypes=[w.LPCWSTR,w.LPCWSTR,w.DWORD];api.OpenSCManagerW.restype=w.HANDLE
    api.OpenServiceW.argtypes=[w.HANDLE,w.LPCWSTR,w.DWORD];api.OpenServiceW.restype=w.HANDLE
    api.QueryServiceStatusEx.argtypes=[w.HANDLE,w.INT,ctypes.c_void_p,w.DWORD,ctypes.POINTER(w.DWORD)]
    api.QueryServiceStatusEx.restype=w.BOOL
    api.CloseServiceHandle.argtypes=[w.HANDLE];api.CloseServiceHandle.restype=w.BOOL
    if include_config:
        api.QueryServiceConfigW.argtypes=[w.HANDLE,ctypes.c_void_p,w.DWORD,ctypes.POINTER(w.DWORD)]
        api.QueryServiceConfigW.restype=w.BOOL
    manager=api.OpenSCManagerW(None,None,0x0001)  # SC_MANAGER_CONNECT
    if not manager: raise Denied('SERVICE_QUERY_FAILED')
    try:
        rights=0x0004|(0x0001 if include_config else 0)  # QUERY_STATUS, QUERY_CONFIG
        service=api.OpenServiceW(manager,SERVICE_NAME,rights)
        if not service:
            if ctypes.get_last_error()==1060: return {'state':'ABSENT'}
            raise Denied('SERVICE_QUERY_FAILED')
        try:
            status=STATUS_PROCESS();needed=w.DWORD()
            if not api.QueryServiceStatusEx(service,0,ctypes.byref(status),ctypes.sizeof(status),ctypes.byref(needed)):
                raise Denied('SERVICE_QUERY_FAILED')
            state=_SERVICE_STATES.get(status.current_state,'OTHER')
            result={'state':state,'win32_exit_code':status.win32_exit,'service_exit_code':status.service_exit}
            if include_config:
                api.QueryServiceConfigW(service,None,0,ctypes.byref(needed))
                if ctypes.get_last_error()!=122 or not ctypes.sizeof(CONFIG)<=needed.value<=8192:
                    raise Denied('SERVICE_QUERY_FAILED')
                buf=ctypes.create_string_buffer(needed.value)
                if not api.QueryServiceConfigW(service,buf,len(buf),ctypes.byref(needed)):
                    raise Denied('SERVICE_QUERY_FAILED')
                config=ctypes.cast(buf,ctypes.POINTER(CONFIG)).contents
                result['start_mode']='MANUAL' if config.start_type==3 else 'OTHER'
                result['account_is_localservice']=(config.account or '').casefold()=='nt authority\\localservice'
            return result
        finally: api.CloseServiceHandle(service)
    finally: api.CloseServiceHandle(manager)

def control(action,*,timeout=_CONTROL_TIMEOUT,clock=time.monotonic,sleep=time.sleep):
    if os.name!='nt': raise Denied('WINDOWS_REQUIRED')
    if action not in ('start','stop','query','delete'): raise Denied('UNKNOWN_OPERATION')
    if action=='delete':
        code=system_tool('sc.exe',[action,SERVICE_NAME])
        return {'status':'PASS' if code==0 else 'NEEDS_HUMAN','exit_code':code}
    began=clock()
    try: before=query_service()
    except Denied:
        return {'status':'NEEDS_HUMAN','exit_code':None,'state':'UNKNOWN','warning':'STATE_QUERY_FAILED'}
    initial=before['state'];target={'start':'RUNNING','stop':'STOPPED'}.get(action)
    if action=='query' or initial=='ABSENT' or initial==target:
        success=initial!='ABSENT' if action=='query' else initial==target
        return {'status':'PASS' if success else 'NEEDS_HUMAN',
                'exit_code':0 if success else 1060,'raw_control_code':None,
                'state':initial,'state_before':initial,'state_after':initial,
                'transitions':[initial],'duration_ms':round((clock()-began)*1000),
                'warning':'ALREADY_IN_TARGET_STATE' if action!='query' and success else None,
                'win32_exit_code':before.get('win32_exit_code'),
                'service_exit_code':before.get('service_exit_code')}
    if initial=='OTHER':
        return {'status':'NEEDS_HUMAN','exit_code':None,'state':initial,'warning':'UNSUPPORTED_STATE'}
    deadline=began+max(0,min(60,float(timeout)))
    # Pending transitions are already in progress; avoid resending a control.
    pending=(action=='start' and initial=='START_PENDING') or (action=='stop' and initial=='STOP_PENDING')
    raw=None if pending else system_tool('sc.exe',[action,SERVICE_NAME])
    transitions=[initial];after=before;query_failed=False
    while True:
        try: after=query_service()
        except Denied:
            query_failed=True;after={'state':'UNKNOWN'};break
        state=after['state']
        if state!=transitions[-1]: transitions.append(state)
        if state==target or state in ('ABSENT','OTHER') or clock()>=deadline: break
        sleep(min(_POLL_INTERVAL,max(0,deadline-clock())))
    reached=after['state']==target
    allowed=raw is None or raw==0 or (action=='stop' and raw==1061) or (action=='start' and raw==1056)
    clean_exit=after.get('win32_exit_code',0)==0 and after.get('service_exit_code',0)==0
    success=reached and allowed and clean_exit and not query_failed
    warning=('TRANSIENT_CONTROL_RESULT' if raw==1061 and success else
             'STATE_QUERY_FAILED' if query_failed else 'STATE_TIMEOUT' if not reached and clock()>=deadline else
             'SERVICE_TERMINATED_WITH_ERROR' if reached and not clean_exit else
             'CONTROL_REJECTED' if not allowed else None)
    return {'status':'PASS' if success else 'NEEDS_HUMAN','exit_code':0 if raw is None else raw,
            'raw_control_code':raw,'state':after['state'],'state_before':initial,
            'state_after':after['state'],'transitions':transitions,
            'duration_ms':round((clock()-began)*1000),'warning':warning,
            'win32_exit_code':after.get('win32_exit_code'),
            'service_exit_code':after.get('service_exit_code')}

def run_service():
    if os.name!='nt': raise Denied('WINDOWS_REQUIRED')
    from .runtime import Agent
    dll=ctypes.WinDLL('advapi32',use_last_error=True)
    HANDLER=ctypes.WINFUNCTYPE(None,w.DWORD)
    MAIN=ctypes.WINFUNCTYPE(None,w.DWORD,ctypes.POINTER(w.LPWSTR))
    class STATUS(ctypes.Structure):
        _fields_=[(n,w.DWORD) for n in ('service_type','current_state','controls_accepted','win32_exit','service_exit','checkpoint','wait_hint')]
    class ENTRY(ctypes.Structure): _fields_=[('name',w.LPWSTR),('main',MAIN)]
    dll.RegisterServiceCtrlHandlerW.argtypes=[w.LPCWSTR,HANDLER];dll.RegisterServiceCtrlHandlerW.restype=w.HANDLE
    dll.SetServiceStatus.argtypes=[w.HANDLE,ctypes.POINTER(STATUS)];dll.SetServiceStatus.restype=w.BOOL
    dll.StartServiceCtrlDispatcherW.argtypes=[ctypes.POINTER(ENTRY)];dll.StartServiceCtrlDispatcherW.restype=w.BOOL
    current={'agent':None,'handle':None,'stopping':False,'state':2}
    def report(state,error=0):
        current['state']=state
        status=STATUS(0x10,state,5 if state==4 else 0,error,0,1 if state in (2,3) else 0,30000 if state in (2,3) else 0)
        if current['handle']: dll.SetServiceStatus(current['handle'],ctypes.byref(status))
    @HANDLER
    def handler(code):
        if code in (1,5):
            current['stopping']=True;report(3)
            if current['agent']: current['agent'].stop_event.set()
        elif code==4: report(current['state'])
    @MAIN
    def service_main(argc,argv):
        current['handle']=dll.RegisterServiceCtrlHandlerW(SERVICE_NAME,handler)
        if not current['handle']: return
        report(2);a=None;error=0;root=None;stage='CONFIG'
        try:
            root=state_root()
            config=json.loads((root/'agent-public.json').read_text(encoding='utf-8'))
            stage='AGENT_INIT'
            a=Agent(root,config);current['agent']=a
            bootstrap=root/'enrollment.bootstrap'
            if not a.state['binding'] and bootstrap.exists():
                stage='BOOTSTRAP'
                def ready():
                    nonlocal stage
                    stage='ENROLLMENT'
                enroll_from_bootstrap(a,bootstrap,on_ready=ready)
            (root/'service-diagnostic.json').unlink(missing_ok=True)
            if current['stopping']: a.stop_event.set()
            else: report(4)
            stage='RUNNING'
            a.run()
        except Exception as exc:
            error=1066
            try:
                if root is not None and root.is_dir(): record_service_failure(root,stage,exc)
            except (OSError,Denied): pass
        finally:
            if a: a.close()
            report(1,error)
    table=(ENTRY*2)(ENTRY(SERVICE_NAME,service_main),ENTRY(None,MAIN()))
    if not dll.StartServiceCtrlDispatcherW(table): raise Denied('SERVICE_DISPATCH_FAILED')
